name: Deploy to Clever Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: agel-outreach-clever-deploy
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CLEVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H push-n3-par-clevercloud-customers.services.clever-cloud.com >> ~/.ssh/known_hosts

      - name: Deploy to agel-outreach
        run: git push git+ssh://git@push-n3-par-clevercloud-customers.services.clever-cloud.com/app_c21e4fc4-9cc7-46f4-86bf-ff0c6bca7425.git HEAD:master --force
